[package]
name = "ci"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.32.0"
bitcoincore-rpc = "0.19.0"
bitcoin_hashes = "0.14.0"
base16 = "0.2.1"
rand = "0.8.5"
rocksdb = { git = "https://github.com/rust-rocksdb/rust-rocksdb", rev = "1cf906dc4087f06631820f13855e6b27bd21b972" }
min-batch = { git = "https://github.com/pragmaxim/min-batch" }
tokio = { version = "1.38.0", features = ["full"] }
tokio-stream = { version = "0.1.15", features = ["sync"] }
pin-project-lite = "0.2"
futures = "0.3.30"
chrono = "0.4.38"
bincode = "1.3.3"
serde = { version = "1.0.203", features = ["derive"] }
clap = "4.5.4"
num_cpus = "1.16.0"
crossbeam = "0.8.4"
