openapi: 3.0.0
info:
  title: Rust Playground API
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://localhost:8082
    description: Local server
paths:
  /blocks/{hash_or_height_or_latest}:
    $ref: ./paths/blocks/{hash_or_height_or_latest}/path.yaml
