[blockchain]
name = "btc"
db_path = "/tmp/chain-indexer"
api_host = "http://127.0.0.1:8332"

[indexer]
db_indexes = ["script_hash", "address"] ## order matters, it affects data layout
tx_batch_size = 1500
