[indexer]
db_path = "/tmp/chain-syncer"
enable = true
min_batch_size = 1000           # Sum of : inputs + outputs + assets/tokens
disable_wal = false
fetching_parallelism = "mild"   # low / mild / high
processing_parallelism = "mild" # low / mild / high

[http]
enable = true
bind_address = "127.0.0.1:3031"
