[indexer]
db_path = "/tmp/chain-indexer"
tx_batch_size = 1000
disable_wal = false

[http]
bind_address = "127.0.0.1:3031"

[bitcoin]
api_host = "http://127.0.0.1:8332"

[cardano]
api_host = "localhost:1337"
socket_path = "/var/lib/cardano-node/db/node.socket"

[ergo]
api_host = "http://127.0.0.1:9053"
