[indexer]
db_path = "/tmp/chain-indexer"
tx_batch_size = 1000
disable_wal = false

[cardano]
api_host = "localhost:1337"
socket_path = "/home/lisak/.cardano/db/node.socket"

[bitcoin]
api_host = "http://127.0.0.1:8332"

[ergo]
api_host = "http://127.0.0.1:8332"
api_key = "****"
